### ISSUE TITLE
Configure pre-commit tool for this repo

### ISSUE THREAD

**Issue by webknjaz** [x612skm/fast-api-todo#2]
* [ ] It can be installed locally via something like this

    ```console
    $ python3 -Im pip install pre-commit
    $ python3 -Im pre_commit install
    ```

* [ ] Install https://pre-commit.ci into this repository (log in and follow the instructions on the web UI)
* [ ] Put an example `.pre-commit-config.yaml` config into the repo:

    ```yaml
    ---

    repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v4.5.0
      hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: name-tests-test
      - id: check-ast
      - id: debug-statements

    - repo: https://github.com/pre-commit/mirrors-mypy.git
      rev: v1.10.0
      hooks:
      - id: mypy

    - repo: https://github.com/asottile/add-trailing-comma.git
      rev: v3.1.0
      hooks:
      - id: add-trailing-comma

    - repo: https://github.com/Lucas-C/pre-commit-hooks.git
      rev: v1.5.5
      hooks:
      - id: remove-tabs

    - repo: https://github.com/pycqa/isort.git
      rev: 5.13.2
      hooks:
      - id: isort

    - repo: https://github.com/PyCQA/pylint.git
      rev: v3.1.0
      hooks:
      - id: pylint
        additional_dependencies:
        - fastapi  # list all other deps here

    - repo: https://github.com/PyCQA/flake8.git
      rev: 7.0.0
      hooks:
      - id: flake8
        additional_dependencies:
        - flake8-cognitive-complexity ~= 0.1.0
        - flake8-docstrings ~= 1.7.0

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1
      hooks:
      - id: yamllint
        args:
        - --strict
    ```

Bonus configs:
* some tools from the above example may need more configs that I didn't provide
* you can make one for pylint via `pylint --generate-rcfile > .pylintrc`
* `.yamllint`:

  ```yaml
  ---

  extends: default

  rules:
    indentation:
      level: error
      indent-sequences: false
    truthy:
      allowed-values:
      - >-
        false
      - >-
        true
      - >-  # Allow "on" key name in GHA CI/CD workflow definitions
        on

  ...
  ```
* example config for flake8: https://github.com/cherrypy/cheroot/blob/main/.flake8
* check out https://pre-commit.com for the generic feel of how this tool works and maybe integrate Ruff there on your own
